"""Corrective RAG (CRAG) for compliance checking.

Naive RAG fails silently: if the first retrieval is weak, the model confidently answers
from irrelevant context. CRAG adds an explicit evaluation layer:

    retrieve -> GRADE relevance -> (if weak) rewrite query + re-retrieve -> generate

Here the grader is a lexical relevance score by default (zero-setup, deterministic). The
compliance notes are generated by grounded rule checks that only cite a policy when that
policy was actually retrieved — so the output is traceable to evidence, not hallucinated.
"""

from __future__ import annotations

import re
from typing import Any

from .retriever import LexicalRetriever, get_retriever

# Below this top cosine score the retrieved context is judged insufficient and we
# trigger a corrective re-retrieval with an expanded query.
RELEVANCE_THRESHOLD = 0.06

# Minimum score for a per-note targeted retrieval to count as grounding that note.
GROUND_FLOOR = 0.05


def _build_query(specs: dict[str, Any]) -> str:
    parts = [
        str(specs.get("material", "")),
        str(specs.get("dimensions", "")),
        str(specs.get("finish", "")),
        str(specs.get("quantity", "")),
    ]
    return " ".join(p for p in parts if p).strip() or "textile manufacturing rfq compliance"


def _expand_query(specs: dict[str, Any], query: str) -> str:
    """Corrective action: broaden the query with policy-domain terms."""
    extra = "tolerance dimension material catalog minimum order quantity finishing labeling regulatory"
    return f"{query} {extra}"


def _parse_qty(quantity: str) -> int | None:
    digits = re.sub(r"[,\s]", "", str(quantity))
    m = re.search(r"\d+", digits)
    return int(m.group()) if m else None


def _generate_notes(specs: dict[str, Any], retriever: LexicalRetriever) -> list[str]:
    """Produce compliance notes, each grounded in a per-note targeted retrieval.

    A note is cited with the policy that retrieval actually surfaces for its topic; if
    retrieval finds nothing above the floor, the note is flagged for manual review
    instead of citing a fabricated source.
    """
    dims = str(specs.get("dimensions", "")).lower()
    material = str(specs.get("material", "")).strip()
    qty = _parse_qty(specs.get("quantity", ""))

    # (should_include, message, grounding_query)
    checks: list[tuple[bool, str, str]] = []
    if "tol" not in dims:
        checks.append((True, "Dimensional tolerance not stated; applying house default.",
                       "dimensional tolerance default millimetre panel"))
    if material:
        checks.append((True, f"Material '{material}' checked against the approved catalog.",
                       "approved materials catalog fabric gsm supplier code"))
    if qty is not None and qty < 500:
        checks.append((True, f"Order quantity {qty} is below the 500-unit MOQ - confirm with buyer.",
                       "minimum order quantity moq units surcharge"))
    elif qty is not None and qty > 25000:
        checks.append((True, f"Order quantity {qty} qualifies for volume pricing - route to strategic sourcing.",
                       "volume pricing large order strategic sourcing"))
    if specs.get("finish"):
        checks.append((True, "Finishing spec present; validate OEKO-TEX compliance and shrinkage allowance.",
                       "finishing dyeing enzyme wash oeko-tex shrinkage"))
    checks.append((True, "Confirm fiber-content and care-label requirements for the destination market.",
                   "fiber content care label country of origin regulatory"))

    notes: list[str] = []
    for include, message, query in checks:
        if not include:
            continue
        hits = retriever.query(query, k=1)
        if hits and hits[0].score >= GROUND_FLOOR:
            notes.append(f"{message} [{hits[0].source}]")
        else:
            notes.append(f"{message} [flagged for manual review - no policy match]")
    return notes


def run_crag(specs: dict[str, Any]) -> dict[str, Any]:
    """Run the corrective-RAG compliance pass and return notes plus evidence."""
    retriever = get_retriever()

    query = _build_query(specs)
    hits = retriever.query(query, k=3)
    top = hits[0].score if hits else 0.0
    relevant = top >= RELEVANCE_THRESHOLD

    corrected = False
    if not relevant:
        # Corrective step: expand the query and retrieve again.
        corrected = True
        query = _expand_query(specs, query)
        hits = retriever.query(query, k=3)
        top = hits[0].score if hits else 0.0
        relevant = top >= RELEVANCE_THRESHOLD

    notes = _generate_notes(specs, retriever)

    return {
        "notes": notes,
        "evidence": {
            "engine": "lexical-tfidf",
            "query": query,
            "corrected": corrected,
            "grade": {"top_score": round(top, 3), "relevant": relevant},
            "sources": [
                {"source": h.source, "score": round(h.score, 3), "excerpt": h.text[:180]}
                for h in hits
            ],
        },
    }
